"""updated price 

Revision ID: ab45ca3b38c2
Revises: 14d3dcbb39ab
Create Date: 2021-06-14 16:56:36.450410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab45ca3b38c2'
down_revision = '14d3dcbb39ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_products', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_products', 'quantity')
    # ### end Alembic commands ###
